global:
  name: consul
  datacenter: single-datacenter
  image: hashicorp/consul:1.12.2
  imageEnvoy: envoyproxy/envoy:v1.22.2
  imageK8S: hashicorp/consul-k8s-control-plane:0.45.0
  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: "1m"

server:
  replicas: 1

ui:
  enabled: true
  metrics:
    enabled: true # by default, this inherits from the value global.metrics.enabled
    provider: "prometheus"
    baseURL: http://prometheus-server

connectInject:
  enabled: true
  default: true
  namespaceSelector: |
    matchLabels:
      connect-inject: enabled
  metrics:
    defaultEnabled: true
    defaultEnableMerging: true
    defaultPrometheusScrapePort: 20200
    defaultPrometheusScrapePath: "/metrics"
    defaultMergedMetricsPort: 20100

controller:
  enabled: true

prometheus:
  enabled: true

